export const recipes = [
  {
    title: "Creamy Pasta",
    time: "30 Min",
    calories: "239 Cal",
    image: "",
    favorite: false,
    description:
      "Cook pasta according to package instructions. In a separate pan, sauté garlic in butter until fragrant. Add cream and bring to a simmer. Stir in Parmesan cheese until melted. Combine pasta with the sauce and garnish with parsley.",
    ingredients: [
      { name: "Pasta", image: "" },
      { name: "Cream", image: "" },
      { name: "Garlic", image: "" },
      { name: "Parmesan Cheese", image: "" },
      { name: "Parsley", image: "" },
    ],
    recipe_type: ["Lunch", "Dinner"],
  },
  {
    title: "Grilled Chicken Salad",
    time: "20 Min",
    calories: "150 Cal",
    image: "",
    favorite: false,
    description:
      "Grill chicken breast until fully cooked. Chop lettuce, tomato, and cucumber. Mix together with grilled chicken slices and drizzle with olive oil.",
    ingredients: [
      { name: "Chicken Breast", image: "" },
      { name: "Lettuce", image: "" },
      { name: "Tomato", image: "" },
      { name: "Cucumber", image: "" },
      { name: "Olive Oil", image: "" },
    ],
    recipe_type: ["Lunch", "Dinner", "Diet"],
  },
  {
    title: "Vegetable Stir Fry",
    time: "25 Min",
    calories: "200 Cal",
    image: "",
    favorite: false,
    description:
      "Heat oil in a large pan. Add garlic and ginger and sauté for a minute. Add broccoli, carrot, and bell pepper, and stir-fry for 5-7 minutes. Add soy sauce and cook for another 2 minutes.",
    ingredients: [
      { name: "Broccoli", image: "" },
      { name: "Carrot", image: "" },
      { name: "Bell Pepper", image: "" },
      { name: "Soy Sauce", image: "" },
      { name: "Ginger", image: "" },
      { name: "Garlic", image: "" },
    ],
    recipe_type: ["Lunch", "Dinner", "Diet"],
  },
  {
    title: "Beef Tacos",
    time: "15 Min",
    calories: "300 Cal",
    image: "",
    favorite: false,
    description:
      "Cook ground beef in a skillet until browned. Fill taco shells with beef, cheese, lettuce, and salsa.",
    ingredients: [
      { name: "Ground Beef", image: "" },
      { name: "Taco Shells", image: "" },
      { name: "Cheese", image: "" },
      { name: "Lettuce", image: "" },
      { name: "Salsa", image: "" },
    ],
    recipe_type: ["Lunch", "Dinner"],
  },
  {
    title: "Chocolate Cake",
    time: "45 Min",
    calories: "400 Cal",
    image: "",
    favorite: false,
    description:
      "Mix flour, cocoa powder, sugar, baking powder, and eggs. Pour the batter into a greased pan and bake at 350°F for 30-35 minutes. Let it cool before serving.",
    ingredients: [
      { name: "Flour", image: "" },
      { name: "Cocoa Powder", image: "" },
      { name: "Sugar", image: "" },
      { name: "Eggs", image: "" },
      { name: "Butter", image: "" },
      { name: "Baking Powder", image: "" },
    ],
    recipe_type: ["Dessert"],
  },
  {
    title: "Caesar Salad",
    time: "15 Min",
    calories: "180 Cal",
    image: "",
    favorite: false,
    description:
      "Chop romaine lettuce and mix with croutons and Parmesan cheese. Drizzle with Caesar dressing and toss to combine.",
    ingredients: [
      { name: "Romaine Lettuce", image: "" },
      { name: "Croutons", image: "" },
      { name: "Parmesan Cheese", image: "" },
      { name: "Caesar Dressing", image: "" },
    ],
    recipe_type: ["Lunch", "Dinner", "Diet"],
  },
  {
    title: "Mushroom Risotto",
    time: "35 Min",
    calories: "320 Cal",
    image: "",
    favorite: false,
    description:
      "Sauté onions and garlic in butter. Add Arborio rice and cook for 2 minutes. Gradually add broth while stirring until rice is tender. Stir in mushrooms, Parmesan cheese, and white wine.",
    ingredients: [
      { name: "Arborio Rice", image: "" },
      { name: "Mushrooms", image: "" },
      { name: "Parmesan Cheese", image: "" },
      { name: "Onion", image: "" },
      { name: "Garlic", image: "" },
      { name: "Butter", image: "" },
      { name: "White Wine", image: "" },
    ],
    recipe_type: ["Lunch", "Dinner"],
  },
  {
    title: "Pancakes",
    time: "20 Min",
    calories: "250 Cal",
    image: "",
    favorite: false,
    description:
      "Mix flour, eggs, milk, and baking powder to form a batter. Pour batter onto a heated pan and cook until bubbles form on the surface. Flip and cook until golden brown. Serve with butter and maple syrup.",
    ingredients: [
      { name: "Flour", image: "" },
      { name: "Eggs", image: "" },
      { name: "Milk", image: "" },
      { name: "Baking Powder", image: "" },
      { name: "Butter", image: "" },
      { name: "Maple Syrup", image: "" },
    ],
    recipe_type: ["Breakfast"],
  },
  {
    title: "Chicken Curry",
    time: "40 Min",
    calories: "350 Cal",
    image: "",
    favorite: false,
    description:
      "Cook chicken in a pot until browned. Add onions, garlic, and ginger, and cook until fragrant. Stir in curry powder, tomatoes, and coconut milk. Simmer until chicken is fully cooked.",
    ingredients: [
      { name: "Chicken", image: "" },
      { name: "Curry Powder", image: "" },
      { name: "Coconut Milk", image: "" },
      { name: "Onion", image: "" },
      { name: "Garlic", image: "" },
      { name: "Ginger", image: "" },
      { name: "Tomatoes", image: "" },
    ],
    recipe_type: ["Lunch", "Dinner"],
  },
  {
    title: "Fruit Smoothie",
    time: "10 Min",
    calories: "150 Cal",
    image: "",
    favorite: false,
    description:
      "Blend banana, strawberries, orange juice, and yogurt until smooth.",
    ingredients: [
      { name: "Banana", image: "" },
      { name: "Strawberries", image: "" },
      { name: "Orange Juice", image: "" },
      { name: "Yogurt", image: "" },
    ],
    recipe_type: ["Smoothie", "Diet"],
  },
  {
    title: "Spaghetti Bolognese",
    time: "30 Min",
    calories: "320 Cal",
    image: "",
    favorite: false,
    description:
      "Cook spaghetti according to package instructions. In a separate pan, cook ground beef until browned. Add onions, garlic, carrots, and tomato sauce. Simmer for 20 minutes. Serve sauce over spaghetti.",
    ingredients: [
      { name: "Spaghetti", image: "" },
      { name: "Ground Beef", image: "" },
      { name: "Tomato Sauce", image: "" },
      { name: "Onion", image: "" },
      { name: "Garlic", image: "" },
      { name: "Carrot", image: "" },
    ],
    recipe_type: ["Lunch", "Dinner"],
  },
  {
    title: "Avocado Toast",
    time: "10 Min",
    calories: "200 Cal",
    image: "",
    favorite: false,
    description:
      "Mash avocado and spread on toasted bread. Squeeze lemon juice on top and season with salt and pepper.",
    ingredients: [
      { name: "Bread", image: "" },
      { name: "Avocado", image: "" },
      { name: "Lemon", image: "" },
      { name: "Salt", image: "" },
      { name: "Pepper", image: "" },
    ],
    recipe_type: ["Breakfast", "Diet"],
  },
  {
    title: "Tomato Soup",
    time: "25 Min",
    calories: "180 Cal",
    image: "",
    favorite: false,
    description:
      "Sauté onions and garlic in olive oil. Add chopped tomatoes and cook until soft. Blend the mixture until smooth and add basil. Simmer for 10 minutes.",
    ingredients: [
      { name: "Tomatoes", image: "" },
      { name: "Onion", image: "" },
      { name: "Garlic", image: "" },
      { name: "Basil", image: "" },
      { name: "Olive Oil", image: "" },
    ],
    recipe_type: ["Lunch", "Dinner", "Diet"],
  },
  {
    title: "Baked Salmon",
    time: "30 Min",
    calories: "250 Cal",
    image: "",
    favorite: false,
    description:
      "Place salmon fillets on a baking sheet. Drizzle with olive oil, and lemon juice, and sprinkle with dill. Bake at 375°F for 20-25 minutes.",
    ingredients: [
      { name: "Salmon", image: "" },
      { name: "Lemon", image: "" },
      { name: "Dill", image: "" },
      { name: "Olive Oil", image: "" },
    ],
    recipe_type: ["Lunch", "Dinner", "Diet"],
  },
  {
    title: "French Toast",
    time: "20 Min",
    calories: "290 Cal",
    image: "",
    favorite: false,
    description:
      "Whisk together eggs, milk, and cinnamon. Dip bread slices in the mixture and cook on a heated pan until golden brown. Serve with maple syrup.",
    ingredients: [
      { name: "Bread", image: "" },
      { name: "Eggs", image: "" },
      { name: "Milk", image: "" },
      { name: "Cinnamon", image: "" },
      { name: "Maple Syrup", image: "" },
    ],
    recipe_type: ["Breakfast"],
  },
];
