export const recipes = [
  {
    title: "Creamy Pasta",
    time: "30 Min",
    calories: "239 Cal",
    image: "",
    favorite: false,
    description: "A delicious and creamy pasta dish perfect for any meal.",
    ingredients: [
      { name: "Pasta", image: "" },
      { name: "Cream", image: "" },
      { name: "Garlic", image: "" },
      { name: "Parmesan Cheese", image: "" },
      { name: "Parsley", image: "" },
    ],
  },
  {
    title: "Grilled Chicken Salad",
    time: "20 Min",
    calories: "150 Cal",
    image: "",
    favorite: false,
    description: "A healthy and refreshing salad with grilled chicken.",
    ingredients: [
      { name: "Chicken Breast", image: "" },
      { name: "Lettuce", image: "" },
      { name: "Tomato", image: "" },
      { name: "Cucumber", image: "" },
      { name: "Olive Oil", image: "" },
    ],
  },
  {
    title: "Vegetable Stir Fry",
    time: "25 Min",
    calories: "200 Cal",
    image: "",
    favorite: false,
    description: "A quick and easy vegetable stir fry.",
    ingredients: [
      { name: "Broccoli", image: "" },
      { name: "Carrot", image: "" },
      { name: "Bell Pepper", image: "" },
      { name: "Soy Sauce", image: "" },
      { name: "Ginger", image: "" },
      { name: "Garlic", image: "" },
    ],
  },
  {
    title: "Beef Tacos",
    time: "15 Min",
    calories: "300 Cal",
    image: "",
    favorite: false,
    description: "Delicious and easy-to-make beef tacos.",
    ingredients: [
      { name: "Ground Beef", image: "" },
      { name: "Taco Shells", image: "" },
      { name: "Cheese", image: "" },
      { name: "Lettuce", image: "" },
      { name: "Salsa", image: "" },
    ],
  },
  {
    title: "Chocolate Cake",
    time: "45 Min",
    calories: "400 Cal",
    image: "",
    favorite: false,
    description: "A rich and moist chocolate cake.",
    ingredients: [
      { name: "Flour", image: "" },
      { name: "Cocoa Powder", image: "" },
      { name: "Sugar", image: "" },
      { name: "Eggs", image: "" },
      { name: "Butter", image: "" },
      { name: "Baking Powder", image: "" },
    ],
  },
  {
    title: "Caesar Salad",
    time: "15 Min",
    calories: "180 Cal",
    image: "",
    favorite: false,
    description: "A classic Caesar salad with creamy dressing.",
    ingredients: [
      { name: "Romaine Lettuce", image: "" },
      { name: "Croutons", image: "" },
      { name: "Parmesan Cheese", image: "" },
      { name: "Caesar Dressing", image: "" },
    ],
  },
  {
    title: "Mushroom Risotto",
    time: "35 Min",
    calories: "320 Cal",
    image: "",
    favorite: false,
    description: "A creamy and flavorful mushroom risotto.",
    ingredients: [
      { name: "Arborio Rice", image: "" },
      { name: "Mushrooms", image: "" },
      { name: "Parmesan Cheese", image: "" },
      { name: "Onion", image: "" },
      { name: "Garlic", image: "" },
      { name: "Butter", image: "" },
      { name: "White Wine", image: "" },
    ],
  },
  {
    title: "Pancakes",
    time: "20 Min",
    calories: "250 Cal",
    image: "",
    favorite: false,
    description: "Fluffy and delicious pancakes.",
    ingredients: [
      { name: "Flour", image: "" },
      { name: "Eggs", image: "" },
      { name: "Milk", image: "" },
      { name: "Baking Powder", image: "" },
      { name: "Butter", image: "" },
      { name: "Maple Syrup", image: "" },
    ],
  },
  {
    title: "Chicken Curry",
    time: "40 Min",
    calories: "350 Cal",
    image: "",
    favorite: false,
    description: "A spicy and flavorful chicken curry.",
    ingredients: [
      { name: "Chicken", image: "" },
      { name: "Curry Powder", image: "" },
      { name: "Coconut Milk", image: "" },
      { name: "Onion", image: "" },
      { name: "Garlic", image: "" },
      { name: "Ginger", image: "" },
      { name: "Tomatoes", image: "" },
    ],
  },
  {
    title: "Fruit Smoothie",
    time: "10 Min",
    calories: "150 Cal",
    image: "",
    favorite: false,
    description: "A refreshing and healthy fruit smoothie.",
    ingredients: [
      { name: "Banana", image: "" },
      { name: "Strawberries", image: "" },
      { name: "Orange Juice", image: "" },
      { name: "Yogurt", image: "" },
    ],
  },
  {
    title: "Spaghetti Bolognese",
    time: "30 Min",
    calories: "320 Cal",
    image: "",
    favorite: false,
    description: "A classic Italian pasta dish with a rich meat sauce.",
    ingredients: [
      { name: "Spaghetti", image: "" },
      { name: "Ground Beef", image: "" },
      { name: "Tomato Sauce", image: "" },
      { name: "Onion", image: "" },
      { name: "Garlic", image: "" },
      { name: "Carrot", image: "" },
    ],
  },
  {
    title: "Avocado Toast",
    time: "10 Min",
    calories: "200 Cal",
    image: "",
    favorite: false,
    description: "A simple and healthy avocado toast.",
    ingredients: [
      { name: "Bread", image: "" },
      { name: "Avocado", image: "" },
      { name: "Lemon", image: "" },
      { name: "Salt", image: "" },
      { name: "Pepper", image: "" },
    ],
  },
  {
    title: "Tomato Soup",
    time: "25 Min",
    calories: "180 Cal",
    image: "",
    favorite: false,
    description: "A warm and comforting tomato soup.",
    ingredients: [
      { name: "Tomatoes", image: "" },
      { name: "Onion", image: "" },
      { name: "Garlic", image: "" },
      { name: "Basil", image: "" },
      { name: "Olive Oil", image: "" },
    ],
  },
  {
    title: "Baked Salmon",
    time: "30 Min",
    calories: "250 Cal",
    image: "",
    favorite: false,
    description: "A healthy and delicious baked salmon.",
    ingredients: [
      { name: "Salmon", image: "" },
      { name: "Lemon", image: "" },
      { name: "Dill", image: "" },
      { name: "Olive Oil", image: "" },
    ],
  },
  {
    title: "French Toast",
    time: "20 Min",
    calories: "290 Cal",
    image: "",
    favorite: false,
    description: "A sweet and tasty French toast.",
    ingredients: [
      { name: "Bread", image: "" },
      { name: "Eggs", image: "" },
      { name: "Milk", image: "" },
      { name: "Cinnamon", image: "" },
      { name: "Maple Syrup", image: "" },
    ],
  },
];
